web:
  container_name: nginx-http
  build: ./nginx
  ports:
    - "80:80"
  volumes:
    - ./app:/var/www/app
    - ./logs/nginx:/var/log/nginx
  links:
    - php
php:
  container_name: php-app
  build: ./php
  ports:
    - "9000:9001"
  volumes:
    - ./app:/var/www/app
npm:
  container_name: npm-app
  build: ./npm
  volumes:
    - ./app:/var/www/app